version: '3'

services:
  restapi:
    image: stoplight/prism:3
    command: >
      mock -h 0.0.0.0 /tmp/openapi.yaml
    volumes:
      - ./rest-api-schema/src/main/resources/openapi.yaml:/tmp/openapi.yaml
    ports:
      - 4010:4010